### ISSUE TITLE
missing permission on files in cit/bin on Windows

### ISSUE THREAD

**Issue by DoertheM** [IBM/ansible-automation-for-lmt#26]
We used the playbook to deploy the agent on Windows. It worked fine, but the scans are not able to be executed with an error 'access denied (error 5 or 0x5 for the scheduled task)'. To verify where the permission are invalid, we have performed all steps manually which will be executed by the scheduled task and the issue is related to permissions in the LMT scanner directory \cit\bin. All files in that folder have no permission assigned: 

_No groups or users have permission to access this object. However, the owner of this object can assign permissions._

The reason is simple. The folder CIT has the permission
Allow everyone - Read - This folder and subfolders
Allow Administrators - Full Control - This folder and subfolders

No user got permission on files, hence all files in the folder cit and and all subfolders got no permission assigned.

For a test I have now added a new command to provide permission in install_scanner_windows.yml:

    - name: "Give FullControl rights to SYSTEM for \cit\bin directory on Windows endpoints"
      ansible.windows.win_acl:
        path: "{{ lmt_scanner_path_windows }}\\cit\\bin"
        user: "SYSTEM"
        type: allow
        rights: Read,Write,Modify,FullControl,Delete
        inherit: ContainerInherit, ObjectInherit
        state: present
        propagation: 'None'

and started the scheduled task which is running under the SYSTEM account. The scan was now successful. But it makes sense to correct the permissions, if you can confirm the bug.
We have tested it on several Windows system 2012-2019.

**Comment by DoertheM** [comment]
Very sad that there is no solution so far. With every update we have to modify the playbooks afterwards to get it working on Windows.

**Comment by anna-glowiak** [comment]
I apologize for the delay. The fix will be applied to the disconnected scanner and released with the next version.

**Comment by anna-glowiak** [comment]
New version of disconnected scanner has been released with IBM License Metric Tool 9.2.34.0.
