### ISSUE TITLE
ansible shell module - args: warn is no longer supported

### ISSUE THREAD

**Issue by rvermausa** [IBM/ansible-automation-for-lmt#30]
If you are not using ansible 2.9 or below you will run into the following issue. 

TASK [ilmt_scanner : Unpack Scanner package on UNIX/Linux endpoints] ********************************
fatal: [<target hostname>]: FAILED! => {"changed": false, "msg": "Unsupported parameters for (ansible.legacy.command) module: warn. Supported parameters include: _uses_shell, stdin, removes, stdin_add_newline, strip_empty_ends, creates, argv, chdir, _raw_params, executable."}

==============================================================================

https://docs.ansible.com/ansible/latest/collections/ansible/builtin/shell_module.html - args: warn is no longer available.
https://docs.ansible.com/ansible/2.9/modules/shell_module.html  - args: warn is still supported.

==============================================================================

I have commented out warn as you can see in below so that it will work:

grep -r "warn: false"

roles/ilmt_scanner/tasks/install_scanner_unix.yml.org:        warn: false
roles/ilmt_scanner/tasks/uninstall_scanner_unix.yml.org:        warn: false
roles/ilmt_scanner/tasks/uninstall_scanner_unix.yml.org:        warn: false
roles/ilmt_scanner/tasks/install_scanner_unix.yml:        #warn: false
roles/ilmt_scanner/tasks/install_scanner_ibmi.yml:        warn: false
roles/ilmt_scanner/tasks/uninstall_scanner_ibmi.yml:        warn: false
roles/ilmt_scanner/tasks/uninstall_scanner_unix.yml:        #warn: false
roles/ilmt_scanner/tasks/uninstall_scanner_unix.yml:        #warn: false

**Comment by anna-glowiak** [comment]
Fix integrated and will be released in 9.2.34 December release.
