### ISSUE TITLE
Token exposed in decommission request

### ISSUE THREAD

**Issue by ursetto** [IBM/ansible-automation-for-lmt#39]
During decommission, a DELETE request is made. The `lmt_server_token` is included in the url. As such, the token will be logged and may be publicly visible, as when used with Ansible Tower.

Please update this to use `no_log: true`.

https://github.com/IBM/ansible-automation-for-lmt/blob/b4ca1d163e83fd175f9878fad4c75167956b5434/roles/ilmt_scanner/tasks/decommission_computer.yml#L2-L11

**Comment by anna-glowiak** [comment]
Fix committed.
