### ISSUE TITLE
Issue with lmt_disconnected_scans_collector.yml 

### ISSUE THREAD

**Issue by bmc1412** [IBM/ansible-automation-for-lmt#8]
Hello,

I am testing this playbook locally , while execution, it is collecting 2 compressed scan files while on endpoint only 1 scan file is present.

Need to fix this behavior, suepecting issue while collecting data.

lmtserver and Ansible on same server: RHEL 7
Endpoint: Ubuntu 16.04.6 LTS (GNU/Linux 4.4.0-141-generic x86_64)

**Comment by bmc1412** [comment]
please note my IBM ID: bharatchaudhari@in.ibm.com

**Comment by arturobrzut** [comment]
During downloading data by playbook we only fetch files
it should not create any additional files
After successfully downloading files, the files will be removed

maybe you schedule running the scan on endpoints twice
Please check the date of scan (and correlate it with running playbook)
If problem persists please send me the problematic zip file

**Comment by DariuszGlocki** [comment]
The collector playbook was completely rewritten in 9.2.22 release (and a bunch of other playbooks have been added). If any the problem still occurs with a new code please re-open a defect
